# -*- coding: utf-8 -*-
"""numpy basic assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wHcbNNfkdlF8_QMicyGOewkYye41AUzL
"""

# Importing NumPy
import numpy as np

# Q1: Difference in data types of list_ and array_list
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Q1: Data types of variables")
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))
print("\n")

# Q2: Data types of each element in list_ and array_list
print("Q2: Data types of each element")
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))
print("\n")

# Q3: Change in data type when dtype=int in array_list
array_list = np.array(object=list_, dtype=int)

print("Q3: Data types after changing dtype to int")
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))
print("\n")

# Q4: Characteristics of num_array
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Q4: Characteristics of num_array")
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)
print("\n")

# Q5: Create a 3x3 matrix of zeros
zeros_matrix = np.zeros((3, 3))
print("Q5: 3x3 matrix of zeros")
print(zeros_matrix)
print("\n")

# Q6: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("Q6: 5x5 identity matrix")
print(identity_matrix)